logging:
  level:
    com.netflix.discovery.DiscoveryClient: WARN
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN

spring:
  jpa:
    properties:
      format_sql: true
      show_sql: true
      jdbc.lob.non_contextual_creation: true
    generate-ddl: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#    hibernate:
#      ddl-auto: validate
#logging:
#  level:
#    root: debug

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    registry-fetch-interval-seconds: 15
    disable-delta: true
    region: ap-northeast-2

kafka:
  topic:
    queue: queue-topic
    match: match-topic
    chat: chat-topic
  address: 127.0.0.1:9092
  group_id:
    match: match-group

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh