logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: ERROR
    com.amazonaws.internal.InstanceMetadataServiceResourceFetcher: ERROR

spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

kafka:
  topic:
    match: match-topic
    chat: chat-topic
  address: 127.0.0.1:9092
  group_id:
    match: match-group

randhand:
  host_ip: localhost
  warm_up: false

firebase:
  path: "{cipher}AQBJXYp7CU1taTv7OnPVlmVUsOzM25g9KRQ4+fPcrcYvwv96nhu8pL5U7FiXNOBYT0nYn5QGPo0Nz5cyaTqGJjK7jIH7X0Q8OlYKGI24Z1DhhsaoLf9On9172OAs5fPR6QQuN+9d9YY0qK+/dU3mI0TKpxOYUQkcNwN3u+3Yl2jLgfGkKHkRzR2E469PmPE1fXyvOMGhCbyLQHa/bsY5JD2y9AbyRSYcrJY6f+h2IcW/G5BBF/WEnxzICFe91ivobiK4Egao+bO+RV/TuflYn1O0zHkBrZN4AWWZI/hVbaBviHql5qOh7h6Cu3zuXrEQxYi6os3rx+ztKHfqvJ999KeYU0oXBMpilTielfSSUHcaqyLSzoyTlyRLvlreODxfdB+b7jvI9W7bzPNDTVXAmnRGe9scQ4W/PKUclP39VcN+BsrfRTOGqWi6kpJgjd5vvtnBqAjmQYi1R88SeC2j9f0wXfxqfl6X5IhCdXGLUv7kj5wCCIIbKN7fsWKTlrtO19c="

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh

redis:
  host: 127.0.0.1
  port: 6379