logging:
  level:
    com.netflix.discovery.DiscoveryClient: WARN
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN

spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
  jpa:
    generate-ddl: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: randhand
    password: "{cipher}AQBl10mSrlqIWxRZFIJLsa+CZKfsOsRjra63oU6Tqq5kYS+bIIWTxxBcNv1Kqg95f3ugEA3ei4bMR89vFZ3oLHav2BWw2cZT7LZNNAjWQksWzRQJfptqwMeqkaz82z/xcTIzfqRI43DQSz/BeV0EHn0Zo9iMLUNH/jSlnuEGp5t/L0XtkKlNtnHNa1lW4waxfLcwP86eyXMYi2IGG87b+1MBtYaJVfC8+mzUjHV2YaTe292t1csSC1E35e2zYvdB73TWnjsxOsjUU3uV0/e9smZF1Q99ULiXQ6oaVrjlhwm7I7gTriXWthIz6lPP+vu31kR8kUGFGuAv8nDvsq9g/yB5kMhrgsVk+gOKNMfQ0lvV667ZK+wARyKRVWD+Ryukcgs="

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    registry-fetch-interval-seconds: 15
    disable-delta: true
    region: ap-northeast-2

kafka:
  topic:
    match: match-topic
    chat: chat-topic
  address: "{cipher}AQBRM86ruc8KkHysg156H4zUJ4zaYP39kShnIizwLW7lEUitdb4p6MEqPPV/i4DeVW3FFqj7DL36/syBQ06Z9z1lo0oSijZb9SuHIBI2YmvkRsMvT4e+hP+Gkume85WbVBUBwBblM3BUXCVmOfqNGCPRDQP3ZHk0cZHWYMH13OTOe6WsIazGOyHE5EK8hRT+c7pCpn2F/IGoJABcnOLwVdZsVB9YSN2qQZTxCH68OflP+3osOUoqMhe52TxNrYilIPBmTvX65i1BcdxyWZXgW3wzXsRgyMsFjYWDZEenVaICSR9kKG5j5FKz+bcmcSeG/mf1bfh/xQp67xEQmxcMmXJ/slp3FOluxOmDmSwurEBGugPRaCIyotSxqnTL252k6dQ4xTbzj52O2Wn8e12XqLh/"
  group_id:
    match: match-group

randhand:
  host_ip: 172.18.0.1
  warm_up: true

firebase:
  path: "{cipher}AQAqqA8tAL+YtVzGik40oXR7MbGzuXiGUpZdz5pOlhGJbx2Mvlvqms0zO3/kSNr19tTu/Veumx+cwCZk1WwCsSUIoKQAMSW0VgaUbcaRav/4klO/XotMYHgE3Vtl2vnNI2xnr2l/Q8eqnaHyUTwGVbdiDAcZGjPyW6vDL1rjzOrHNED1vmnEHKVrWG/UCeKICZQ2UyJhJf90e+9W8Vyar8kmvetOOA0/aj7bzkNzWQcqb2ZIWCPCI07zqMw2+xcLrhaZDlQ257NkglbhrGmfCUuxKD5WBr761zHdgXF3wWJu/C/kt+fnQGfrrf0V5vONayCzt8WC3Vf2tq9T7g5jRGlA8Aze/EgGwboZhb2Ew0ci+0CcVtKeLpiREyGdN72F2xhkTawAqYm7G0tc7mDM4Ccd"

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh

redis:
  host: "{cipher}AQAIsXjFP80NA3ytOwat45Pwa6UE4sIII4LcW1QMw5hvX/GqCOWBYAt+vzTSWeKxtcXUkKFvlRsvjrEA5ng1ldOezjz9siaNPfEpYTBcVeteMAWxp4TfBJrlfqmla18tXfvos9Z2FaJMm4JCriVhjehhOAyhkR/k82d/o9z/jkTGGCmMt7Xu3VbcJl6yfmL22UdQnONmIRl4ujayyPXGkBw3oXm/QsGw1t8mFwXdKnvZ7/Euz/NuDk6Dz4aG+P8WmMJ7aKh1Th+KCWCW2CoIZMnyRwxZK2KkJVNc7h0kaFrqNriSt0DLlAacElBk4YHt+TaxWUYyyBkWu5e2J7sac4Tj7+O9pPsI4F+5l0qINU+/OirQTYpeBrrHIXVK7OfzxZgRG1C9XfQwaPrZljRCaM7mkqrQLX5YCtHO1YkfkIURxr7Z8skmGU+RaZEKWH+mUGQ="
  port: 6379