eureka:
  client:
    eureka-service-url-poll-interval-seconds: 30

spring:
  cloud:
    gateway:
      routes:
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/health
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}

        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}

        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/users
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}

        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}

        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: gesture-service
          uri: lb://GESTURE-SERVICE
          predicates:
            - Path=/gesture-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/gesture-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

      default-filters:
        - name: GlobalFilter
          args:
            preLogger: true
            postLogger: true

      httpclient:
        websocket:
          max-frame-payload-length: 3072000