logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: ERROR
    com.amazonaws.internal.InstanceMetadataServiceResourceFetcher: ERROR

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

kafka:
  topic:
    match: match-topic
    chat: chat-topic
  address: 127.0.0.1:9092
  group_id:
    match: match-group

randhand:
  host_ip: localhost
  warm_up: false

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh